<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<title>Mongo DB Test</title>
	</head>
	<body>
		<h1>Mongo DB Test</h1>
		
		<table border=1>
			<tr><td>Database Name</td><td>Size</td><td>Collection Names</td></tr>
			<?php 
			foreach ($Databases as $DatabaseInfo)
			{
			    echo "<tr><td>".$DatabaseInfo['name']."</td><td>".$DatabaseInfo['sizeOnDisk']."</td><td>".implode(', ', $DatabaseInfo['collectionNames'])."</td></tr>";
			}		
			?>
		</table>
		<div>The database information took <?php echo round(1000000*$DatabaseInformationTime, 1);?> micro-seconds</div>

		<div>Have <?php echo $TitleCount;?> objects in the Title collection (took <?php echo round(1000000*$CountTime, 1); ?> micro-seconds)</div>
		<div>Found <?php echo $Cursor->count(true);?></div>
		<div>The query took <?php echo round(1000000*$QueryTime, 1);?> micro-seconds</div>
		<table border=1>
			<tr><td>Title</td></tr>
			<?php 
			foreach ($Cursor as $Object)
			{
			    echo "<tr><td>".$Object["title"]."</td></tr>";
			}		
			?>
		</table>
	</body>
</html>